#!/bin/env bash
#
# @(#) writes script for job submission to sun grid engine -- daniel price 17/2/03
#
if [ $# -lt 1 ]; then
   echo "Usage: $0 infilename [ncpus] [mem]";
else
   filename=$1
   sgename=$filename.pbs
   echo $filename
   if [ $# -gt 1 ]; then
      ncpus=$2;
   else
      ncpus='8';   ## default ncpus
   fi
   echo 'ncpus = '$ncpus
   if [ $# -gt 2 ]; then
      mem=$3;
   else
      mem='1gb';    ## default ncpus
   fi   
   echo 'mem = '$mem
   jobname='booga'$ncpus

#--------------------- print the script -------------------------------

echo "Writing PBS script to file $sgename: jobname '$jobname'"
echo '## PBS Script, created '`date` > $sgename
echo '#PBS -S /bin/csh'   >> $sgename            ## run in csh
echo '#PBS -q devel'  	  >> $sgename		 ## run in this queue
echo '#PBS -l ncpus='$ncpus  	    >> $sgename		 ## number of cpus
echo '#PBS -l mem='$mem  	    >> $sgename		 ## memory
echo '#PBS -l walltime=4:00:00'	    >> $sgename		 ## wall time HH:MM:SS
echo '#PBS -m bae    '	            >> $sgename		 ## email me
echo '#PBS -M dprice@ast.cam.ac.uk' >> $sgename		 ## email me
echo '#PBS -o '$PWD'/'$filename'.output' >> $sgename	 ## job output
echo '#PBS -o '$PWD'/'$filename'.errors' >> $sgename	 ## job errors
echo '#PBS -N '$jobname                  >> $sgename	 ## job name
echo 'setenv MP_SLAVE_STACKSIZE 67108864' >> $sgename
echo 'setenv OMP_SCHEDULE "guided, 1"   ' >> $sgename
echo 'setenv OMP_NUM_THREADS '$ncpus >> $sgename
echo 'setenv MPC_GANG OFF             ' >> $sgename
echo 'cd '$PWD                          >> $sgename
echo './sph_gradh evolution '$filename   >> $sgename
fi
